### ISSUE TITLE
Implement Copy Functionality for Grid Layout Code

### ISSUE THREAD

**Issue by Frenziecodes** [Frenziecodes/gridolia#11]
Make it easy for users to copy the HTML and CSS code that creates the grid layout. To do this, we can add a button in the configuration column, which we'll call "Generate Code." When users click this button, a window will pop up displaying the code that they can copy.
The window, also known as a modal, will have two buttons: "Copy" and "Close." Clicking the "Copy" button will copy the code to the user's clipboard, while the "Close" button will simply close the modal.
To provide feedback, when the user clicks the "Copy" button, the button's label will temporarily change to "Copied" for 3 seconds (3000 milliseconds) using a timeout. After the timeout expires, the button will revert back to its original label, which is "Copy."
For consistency, the "Copy" button can have the same visual style as the "Generate Grid" button.

**Comment by swarajp688** [comment]
@Frenziecodes I would love to work on this issue.

**Comment by Frenziecodes** [comment]
Hello [@swarajp688](https://github.com/swarajp688),
Thank you for expressing interest in this project. I appreciate your enthusiasm! I have assigned the issue to you, and you can proceed with working on it. If you have any questions or need assistance, feel free to reach out.
Happy coding!

**Comment by Frenziecodes** [comment]
@swarajp688 yes ,you can create a components folder.

**Comment by Frenziecodes** [comment]
completed
